### ISSUE TITLE
Porcupine Issue: NextJS Support

### ISSUE THREAD

**Issue by djnugent** [Picovoice/porcupine#1022]
### Expected behaviour
I would like to use Porcupine with NextJS but server side rendering fails because porcupine tries to access window on import. Is there an example of how to use porcupine with NextJS?

### Actual behaviour
Runtime error complaining that window doesn't exist.

### Steps to reproduce the behaviour

`import { usePorcupine } from "@picovoice/porcupine-react";`
on a nextJS page

**Comment by mrrostam** [comment]
Our React binding relies on the [web-voice-processor](https://github.com/Picovoice/web-voice-processor), which necessitates access to the `window` object. Therefore, there are two alternatives: either perform `import` on the client side or utilize [our web binding](https://www.npmjs.com/package/@picovoice/porcupine-web) directly.

**Comment by tannerpace** [comment]
you should be able to  use 'use client' in a dynamic import in your next JS application in order to have it render on the client.import dynamic from
// Import necessary dependencies
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useState, useEffect } from 'react';

// Dynamically import YourComponent
const YourComponent = dynamic(() => import("@components/Forms/YourComponent"), { ssr: false });

// Export the component
export default function YourPage() {
  // YourPage component code here

  return (
    <div>
      <Head>
        <title>Your Page</title>
      </Head>
      {/* Render YourComponent */}
      <YourComponent />
    </div>
  );
}

**Comment by djnugent** [comment]
I was able to solve the issue by creating a component that uses the porcupine library and then dynamically importing the component with SSR disable like @tannerpace suggested. Adding documentation for NextJS would be useful for future users.
