### ISSUE TITLE
Microphone access (from other unity code) while porcupine is active

### ISSUE THREAD

**Issue by ibytergj** [Picovoice/porcupine#1166]
I would like to understand how porcupine interacts with other processes in the same unity app that need access to the microphone. 

For example we are using Inworld.ai (NPC). We have inworld muted and use porcupine to detect a wake word and then activate Inworld to listen to the microphone and respond to input. While porcupine is still active Inworld is not receiving any mic input. If I call _porcupineManager.Stop(); then inworld starts receiving the mic input.

Any suggestion on how I can make these two co-exist? If possible, I would like to have porcupine active all the time and use it to enable Inworlds access to the mic input on demand.

**Comment by laves** [comment]
I'm not sure how Inworld.ai operates their recording, but it sounds like it is taking control of the microphone when it is engaged. If this is the case, then you will not be able to use `PorcupineManager` alongside it. You will have to manage audio capture yourself and pass the audio to an instance of the [Porcupine](https://github.com/Picovoice/porcupine/blob/master/binding/unity/Assets/Porcupine/Porcupine.cs) class and then give that other software the same audio separately. This is not an issue with Porcupine and we are not able to provide integration support via this forum, so I'm going to close the issue.

**Comment by ibytergj** [comment]
I think you misunderstood me and have it backwards. What I stated was that when porcupine is active, it is blocking other process's access to the microphone. When porcupine is disabled then the other app receives mic input no problem. When porcupine is re-enabled the other app stops getting  mic input again.

**Comment by laves** [comment]
I see - apologies for the confusion. Have you tried it the other way around? i.e. run Porcupine (leave it running) and activate your other audio software? My guess is it would stop Porcupine from receiving audio in that case. In general, it is better not to simultaneously run plugins with their own audio capture because it can have unintended consequences on different platforms. I would still suggest either running one at a time (e.g. run Porcupine til the keyword is found and then run your other software) or manage audio capture yourself and send it to the individual plugins as needed.
