### ISSUE TITLE
Build on linux arm 

### ISSUE THREAD

**Issue by littlepeaya** [Picovoice/porcupine#1182]
Hello team, 
I am a developer in Lumi Company, Viet Nam. I am trying to demo your project in my product. My product is linux-arm architecture. I could not find the shared library for my platform of your repository. So, How can i use it?

**Comment by mrrostam** [comment]
@littlepeaya, we don't have a Linux ARM shared library available since our products are optimized for specific architectures. While you could potentially use libraries designed for Raspberry Pi or Jetson Nano (both essentially `Linux ARM`), there's no guarantee they will function (optimally) on your platform.

Alternatively, when you're prepared for a more formal engagement, you can [contact our sales team](https://picovoice.ai/pricing/) to inquire about this support through an enterprise package.
