### ISSUE TITLE
Python logic doesn't validate multi-CPU systems properly

### ISSUE THREAD

**Issue by hellofanengineer** [Picovoice/porcupine#1188]
### Expected behaviour
Use the python porcupine library on a system with an arm cortex-a72-aarch64 processor.

### Actual behaviour
The logic in https://github.com/Picovoice/porcupine/blob/master/binding/python/_util.py only checks the first CPU of a system with multiple CPUs. This can lead to wrongly reporting that the CPU is not supported if the first CPU is not supported but one or more of the other CPUs are. The RockChip 3588 for instance has A55 and A72 processors but lists the A55 first in /proc/cpuinfo. The code incorrectly rejects the CPU of the A55 even though the A72 is supported. If I modify the logic to instead look for any supported processor, it works on my system.

### Steps to reproduce the behaviour
Run `import pvporcupine` in Python on a RockChip 3588.

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
So that you know, we don't support RockChip officially.

There is no guarantee which core the program will run on, and the `so` is built to run on a specific cortex. We can't support this scenario. What is possible is you pass the library path manually to the Python binding (there is an input argument for that) and pick a `so` that would run on both cores (something like `a53`, maybe)
