### ISSUE TITLE
Porcupine Documentation Issue: Rust compilation for IMX8 (arm cortex-a53)

### ISSUE THREAD

**Issue by YossefAboukrat** [Picovoice/porcupine#1227]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/pvrecorder-rust/

### What is the nature of the issue?

Hello, I compiled a project in Rust that uses Porcupine for an i.MX8, but I encountered an error:

`PorcupineError { status: ArgumentError, message: "Couldn't find Porcupine's dynamic library at /target/aarch64-unknown-linux-gnu/release/build/pv_porcupine-5cffce3a0e428628/out/lib/raspberry-pi/cortex-a53-aarch64/libpv_porcupine.so", message_stack: [] }`

Do you support compilation for i.MX8?

**Comment by ErisMik** [comment]
i.MX8 is not an officially supported platform, however it seems that Porcupine is detecting an appropriate library so it seems like it will run when working correctly. 

The error you are getting is that the Porcupine Rust SDK cannot find the library file (`libpv_porcupine.so`) it needs to load to run. Are you by chance moving the compiled rust executable to another directory/device? By default we inject a path to the appropriate library so that it works out of the box with `cargo run`, however if you are moving the executable you will need to use the [PorcupineBuilder.library_path()](https://picovoice.ai/docs/api/porcupine-rust/#porcupineporcupinebuilderlibrary_path) function to manually supply the path to the library, and the library will need to be copied to the target device. You can see / download the appropriate library file for this platform [here](https://github.com/Picovoice/porcupine/tree/master/lib/raspberry-pi/cortex-a53-aarch64) OR it is also packed into the Rust package (the error message gives you a hint as to where it is).

**Comment by YossefAboukrat** [comment]
@ErisMik Awesome, thank you, it works!
