### ISSUE TITLE
Porcupine Issue: PvPorcupine fails to upload dSYM to App Store Connect

### ISSUE THREAD

**Issue by r-token** [Picovoice/porcupine#1311]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Porcupine docs
- [X] I have searched the existing issues for Porcupine

### SDK

iOS

### Porcupine package version

3.0

### Framework version

All Swift versions

### Platform

iOS

### OS/Browser version

All iOS versions

### Describe the bug

After uploading my iOS app to App Store Connect, I get warnings that the archive's dSYM folder is missing DWARF files for two Picovoice frameworks:
- PvPorcupine.framework
- PvRhino.framework

### Steps To Reproduce

1. Build and archive an iOS app that uses Porcupine or Rhino (I'm using Xcode 16)
2. Upload the archive to App Store Connect
3. After the upload completes, you'll see the warnings that the archive did not include a dSYM for PvPorcupine.framework and PvRhino.framework

<img width="960" alt="pico-missing-dsyms" src="https://github.com/user-attachments/assets/66621e54-dbae-4e90-ac22-20241fc9d390">

### Expected Behavior

Those frameworks should include dSYMs that get included with the archive when uploaded to App Store Connect.

**Comment by ksyeo1010** [comment]
Thanks for reporting, will let the team know but cannot provide an exact estimate for a fix. Will let you know once there is a new patch for this.

**Comment by laves** [comment]
@r-token - after some investigation, it seems there is not anything we can do to remove this warning for you. This warning is new to XCode 16 and is simply there to let you know that you will be unable to debug our framework or receive detailed crash reports from it (see [this Apple dev thread](https://developer.apple.com/forums/thread/761589)). The contents of our `PvPorcupine.framework` are closed-source, so we are unable to provide debug symbols to users. As you can see in the adjacent warnings, Google and Firebase are also not shipping debug symbols - likely for the same reason. Since these are just warnings, you can ignore them and they should not impact your application.
