### ISSUE TITLE
Availability of  french(canadian) ressource-files ?

### ISSUE THREAD

**Issue by CarlosLatour** [Picovoice/Porcupine#144]
Love how well & efficiently it works,
is there a way to create 'french' keywords ? (french canadian prefered, but int.french would good too)
Thanks!
PS: This if for non-commercial usage,

**Comment by CarlosLatour** [comment]
Love how well & efficiently it works,
is there a way to create 'french' keywords ? (french canadian prefered, but int.french would good too)
Thanks!
PS: This if for non-commercial usage,

**Comment by petem001** [comment]
Carlos, if you are in the montreal region I would like to have a chat with you.
Been looking at that software for ham radio use and I live in repentigny.



________________________________
De : CarlosLatour <notifications@github.com>
Envoyé : 13 février 2019 19:44
À : Picovoice/Porcupine
Cc : Subscribed
Objet : [Picovoice/Porcupine] Availability of french(canadian) ressource-files ? (#144)

Expected behavior
Actual behavior
Steps to reproduce the behavior

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by CarlosLatour** [comment]
Sure,
(Laval here)

Guess you want to configure it so that it automatically open
repeater-links/autopatch ?
(seem to remember some youtuber doing that with alexa-avs .. , found his
solution a bit 'convoluted'  :-)

It is a lot easier for me via email.. (been dealing with some medical
issues and I cannot always schedule things :(
Alternatively, saturday pm could work.

Carlos Latour
Ve2cio

**Comment by petem001** [comment]
Nice! Send me a private email if you can

Petem001@hotmail.com<mailto:Petem001@hotmail.com>

Pierre
Ve2pf

Envoyé de mon iPad

Le 13 févr. 2019 à 21:47, CarlosLatour <notifications@github.com<mailto:notifications@github.com>> a écrit :

Sure,
(Laval here)

Guess you want to configure it so that it automatically open
repeater-links/autopatch ?
(seem to remember some youtuber doing that with alexa-avs .. , found his
solution a bit 'convoluted' :-)

It is a lot easier for me via email.. (been dealing with some medical
issues and I cannot always schedule things :(
Alternatively, saturday pm could work.

Carlos Latour
Ve2cio

**Comment by kenarsa** [comment]
Thanks for the kind words. We currently only support English. Support for other languages is in our roadmap. I don't have any timing information for French at the moment.
