### ISSUE TITLE
Not able to add Porcupine manager as a dependency 

### ISSUE THREAD

**Issue by rohitpuriji** [Picovoice/Porcupine#189]
### Expected behavior
Porcupine Manager was supposed to add child dependency named porcupine itself.

### Actual behavior
I am not able to add porcupine as dependency because of symlinks created in library.

### Steps to reproduce the behavior

In linux os, if i talk about earlier version i was able to add porcupine as dependency in my project and while adding it says that porcupine manager has further library dependency named porcupine. But with the latest version there are some symlink with porcupine folder and so whenever i tried to add Porcupine manager as a project dependency, its not able to add porcupine library itself.

 Please suggest @kenarsa.

**Comment by kenarsa** [comment]
We do develop on Ubuntu 16.04/18.04 and have not experienced this issue.

Please provide step-by-step instructions on how to reproduce it.

Also if the missing Porcupine dependency is the problem you can add it manually yourself.

**Comment by rohitpuriji** [comment]
What is the symlinks inside porcupine folder ?

**Comment by kenarsa** [comment]
Porcupine binding has symlinks to https://github.com/Picovoice/Porcupine/tree/master/lib/android
If you build it first then you should be able to add since everything will be packaged. If you want to add the sources in a different directory structure then you can simply replace symlinks with actual files. On Linux boxes you can find all symlinks in a directory using "find . -type l -ls".

**Comment by rohitpuriji** [comment]
Thanks manually adding all files instead of symlinks are working now.
