### ISSUE TITLE
WASM build size increased 50% from v1.6->v1.7

### ISSUE THREAD

**Issue by mikob** [Picovoice/porcupine#268]
1.4M -> 2.1M

Build size is obviously critical on the web, so this is a pretty serious increase. Perhaps there was some mistake when making the build? 

On the bright side, the size of pv_porcupine.js decreased from 29K -> 19K.

**Comment by dbartle** [comment]
The WASM size increase in 1.7 stems from significant accuracy upgrade that requires more space, so the size is within the expected range and not due to a build error.

I agree that every byte counts on the web. In this case the tradeoff the performance boost is too much to pass up while still keeping it at a (relatively) reasonable size.
