### ISSUE TITLE
Upgrading to 1.8 issues

### ISSUE THREAD

**Issue by prashanthsridhar** [Picovoice/porcupine#280]
Currently using porcupine manager to detect keyword in an angular project.

The implementation is as follows:

`this.porcupineManager.start(this.KEYWORDS_ID, this.SENSITIVITIES, this.detectionCallback.bind(this), this.errorCallback); `

detectionCallback is the function called when keyword is hit.

these are files which are included:

![image](https://user-images.githubusercontent.com/11289456/84123854-0969e400-aa58-11ea-9334-c24ec7397854.png)

How do i update to the latest version of porcupine or porcupine manager without having to implement my own `getNextAudioFrame`.

**Comment by dbartle** [comment]
Porcupine 1.8 does not change or break any interface and is a drop-in upgrade (along with 1.8 keyword models).

We coincidentally updated the JavaScript/WASM demo code around the time of release of 1.8, but those changes are orthogonal to Porcupine 1.8.

I am assuming that you updated the repo and are referencing the the **demo** source files directly? If you check the recent commits you can see how to update your code to use them. Or, you can simply use the older versions from a week ago and they continue to work.

Either way, the demo code is provided for sample implementation but we recommend against linking directly to the demo source files because we don't guarantee any sort of compatibility (even within a version of porcupine).
