### ISSUE TITLE
Help on install porcupine to raspberrypi as google assistant hotword.

### ISSUE THREAD

**Issue by thrylosthyra7** [Picovoice/porcupine#318]
Hello.I'm trying to install porcupine to raspberrypi 3 as a hotword to my google assistant.
The steps I follow are described [here](https://pimylifeup.com/raspberry-pi-porcupine/).
So I first correctly identify my sound card.(mic and speakers).
Then I install pvporcupine and I try this command:`pvporcupine_mic --keywords porcupine
` ,
which should start listening for my keyword. But it returns this error:`bash: pvporcupine_mic: command not found`
It won't let me proceed further.
Does anyone have an idea how to solve this problem?
Thanks in advance!

**Comment by dbartle** [comment]
It looks like some things have changed since that blog post was published. Here's the official Picovoice doc quick start: https://picovoice.ai/docs/quick-start/porcupine-python/. The file and microphone demos are part of the new 'pvporcupinedemo' package. If you encounter anything out of date in the official docs, please let us know.
