### ISSUE TITLE
React Native - Background Recording for Android

### ISSUE THREAD

**Issue by juraam** [Picovoice/porcupine#338]
When I called start method of porcupine manager, it wasn't recording and recognising wake word when app went to background or device is blocked. As I understood, in Android I should create foreground service, which recording and recognising. So how can I create porcupine manager inside foreground service?

**Comment by laves** [comment]
Our Porcupine React Native package is designed to be fully cross-platform so we intentionally avoided any platform-specific enhancements such as Android foreground service. However, it seems to be quite possible to add a foreground service to your app, so it should be possible to use PorcupineManager from it.

Here's some resources:
https://github.com/voximplant/react-native-foreground-service
https://medium.com/javascript-in-plain-english/react-native-foreground-service-f7fc8e617fba

**Comment by jordan-tpz** [comment]
@laves I tried to add a foreground service in my app by following [this tutorial](https://medium.com/javascript-in-plain-english/react-native-foreground-service-f7fc8e617fba). I would like your feedback about my code (during create the task) : 

```js
ReactNativeForegroundService.add_task(
  () => {
    this._porcupineManager.start()
      .then((didStart) => {
        if (didStart) {
          ...
        }
      })
      .catch((err) => {})
    ;
  },
  {
    delay: 0,
    onLoop: false,
    taskId: 'taskid',
    onError: (e) => console.log(`Error logging:`, e)
  }
);
```

**My main question :** according to you, do you think it's correct ? Or would you call `PorcupineManager.fromKeywords()` function (which contains the detection callback) instead the function `this._porcupineManager.start()` ?

**Comment by laves** [comment]
Good to hear you were able to get Porcupine on a foreground service. It looks fine to me, but unfortunately, I can't help you with this particular issue, as I haven't done a foreground service in React Native before. You're just going to have to test it out and see how it works! If there are any issues with the React Native SDK during the process, let us know.

**Comment by jordan-tpz** [comment]
@laves thanks for your feedback and I understand what you said. It seems to work fine to me ! The porpucine detection callback is triggered when my app went to background or device is blocked !

**Comment by juraam** [comment]
@jordan-tpz and where did you call stop of porcupine manager?
Or did you just remove task from ReactNativeForegroundService ?

**Comment by jordan-tpz** [comment]
@juraam I use two main functions in my app : `startRecordingHotword()`and `stopRecordingHotword()`

- In the `startRecordingHotword()`function :

I register the task (as I have mentionned [here](https://github.com/Picovoice/porcupine/issues/338#issuecomment-754049310)) in order to add a foreground service for that. Then I start the task using `ReactNativeForegroundService.start()` (if you use [this package](https://www.npmjs.com/package/@supersami/rn-foreground-service))

- In the `stopRecordingHotword()` function :

I check if that task is running (using `ReactNativeForegroundService.is_task_running()`. If true, I delete it by calling `ReactNativeForegroundService.remove_task()`. Then, I stop audio capture and wake word detection by calling `this._porcupineManager.stop()`.

I don't know if it's the better way for this.. But this works fine in my app.

**Comment by juraam** [comment]
@jordan-tpz 
Yes, I use this package too :)
Yes, I understood your code, but what about case when I shut down app with swipe(as I understood, foreground service remains active and goes to headless mode) and then I relaunched app. We have no link to porcupineManager, so how can we stop its?

**Comment by jordan-tpz** [comment]
@juraam I tried your case. For my app, when I shut down it with swipe, the foreground service remains active (the notification remains in my phone). When I relaunched app, I can always use Porcupine because the detection callback continue to work. But effectively, the foreground service is never stopped during this case. So, do you think it's a problem ?

**Comment by juraam** [comment]
@jordan-tpz after a many tests I wrote my own android module, which works as service(like in documentation), because package React Native Foreground service loads js thread(as I understood from my tests)

**Comment by jordan-tpz** [comment]
@juraam thank you for your feedback ! Well done for your module. Does your module include the Porcupine manager ?
But, I don't understand what is the problem if the package React Native service load js thread ? Do you think this will cause a loss of performance for the app or something else ?

**Comment by rafaelpoa** [comment]
> [@jordan-tpz](https://github.com/jordan-tpz) after a many tests I wrote my own android module, which works as service(like in documentation), because package React Native Foreground service loads js thread(as I understood from my tests)

Hello my friend, how are you? I'm developing a similar project, could you share with me what you created?
