### ISSUE TITLE
Node.js native module for ARM11 (Raspberry Pi 1 and Zero)

### ISSUE THREAD

**Issue by mguella** [Picovoice/porcupine#341]
Native node modules for Raspberry Pi 2, 3 and 4 are [already provided](https://github.com/Picovoice/porcupine/tree/master/lib/node/raspberry-pi), but given that Porcupine works on Raspberry Pi Zero too, could you please also provide the Node.js native module compiled for ARM11?
Thanks!

**Comment by kenarsa** [comment]
Is NodeJS officially supported on RPI0? I was on the impression, No. If that's not the case please provide pointers and we will be happy to learn more.

**Comment by mguella** [comment]
The Pi Zero is officially supported till version 11.x of Node and the official ARMv6 binaries are still available (Node 10.x LTS is in maintenance, but has not reached end of life yet)
https://nodejs.org/download/release/v10.23.1/
https://nodejs.org/download/release/v11.15.0/

This means that people can still install the official Node 10.x build on Pi Zero with Raspian and APT by using the default repository list.

Starting from 12.x Node removed official support for ARMv6, but they keep providing unofficial builds, so it’s possible to use the latest version too on Pi Zero:
https://unofficial-builds.nodejs.org/download/release/v14.9.0/
https://unofficial-builds.nodejs.org/download/release/v15.5.1/

**Comment by dbartle** [comment]
While it appears _possible_ to run Node on the Pi Zero, the lack of new packages and official builds signals it not being a priority, and therefore does not make much sense for us to support.

If you wish to use Node 10 on Pi Zero, you do have the option to use the FFI approach: [https://github.com/node-ffi/node-ffi](https://github.com/node-ffi/node-ffi). The previous version of the Porcupine bindings were written this way. Indeed you can find the complete source for the FFI bindings in this repo: https://github.com/Picovoice/porcupine/commit/c3b27e1f57230ab84b80d6cae215fab3af80e60e#diff-cd0d91b264f0bc4111a09ae4e915eb600eb843730ac542dce7c928cc0e0d8aa6.

We can't provide any support for it, and indeed we moved away from it due to issues with node 12/14+. In theory, the node-ffi / node-ffi-napi libraries can also provide support for higher versions of node as well, but there were some major blocking issues in those libraries as of 3 months ago.
