### ISSUE TITLE
PicoVoice Console Train Wake Word For Platform Raspberry Pi Restricted

### ISSUE THREAD

**Issue by slowrunner** [Picovoice/porcupine#342]
Using "Personal Account" to train wake word for Raspberry Pi 3B based GoPiGo3 robot.  Porcupine demo with keyword "porcupine" works absolutely amazing, but my robot's name is "Carl", so I would like to program "Wake Up Carl", "Carl", and "Listen Carl" for my wake keywords.

Raspberry Pi is listed under "Restricted Platforms" and is not selectable.  I cannot find info about this restriction in any doc page, FAQ, Blog or product page.

### What is the URL of the doc?

https://console.picovoice.ai/ppn

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
![Cannot Choose RPi](https://user-images.githubusercontent.com/8950202/103592162-4c8e1780-4ec0-11eb-99d5-8d65208cf300.png)

**Comment by dbartle** [comment]
On the console signup page, it lists that personal accounts do _not_ have access to "Train Porcupine Wake Word Models": [https://picovoice.ai/docs/quick-start/console-signup/](https://picovoice.ai/docs/quick-start/console-signup/).

The three platforms listed with Porcupine and training allowance were essentially grandfathered in for personal accounts, and they remain because of not wanting to remove features previously available.

With the release of Porcupine 1.9.0, we've included several more free Apache 2.0 wake words including "Computer" and "Jarvis", intended specifically for such projects, due to the number of requests for them. I recommend using one of those for Raspberry Pi. Here's the folder with all of them: https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/raspberry-pi
