### ISSUE TITLE
Difference Between Model and Keyword Files

### ISSUE THREAD

**Issue by jp-ertola** [Picovoice/porcupine#523]
### What is the URL of the doc?
https://picovoice.ai/docs/api/picovoice-c/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
What is the difference between model files and keyword/context files for Porcupine?  The link to the model files takes me to the keyword files directory in the Porcupine repo.  

Thanks,
JP

**Comment by mrrostam** [comment]
The model files (or .pv files) are the common parameters required by the engine. As mentioned in the doc the standard models are available [on GitHub](https://github.com/Picovoice/porcupine/tree/master/lib/common) and it's the same for all keyword files as long as the language does not change. However, keyword files (aka .ppn files) are specific for each keyword and you may need to generate a custom one using [Picovoice Console](https://console.picovoice.ai/). 

The link for the porcupine model files in the doc wrongly was pointing to the keyword directory instead of the common param directory, and it will be fixed shortly
