### ISSUE TITLE
Porcupine Issue: pvporcupine.create hangs

### ISSUE THREAD

**Issue by yuanzhaoz** [Picovoice/porcupine#579]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Create the handler object

### Actual behaviour
Create() functions hangs indefinitely

### Steps to reproduce the behaviour

I tried the latest verionsn (2.0.0 and 2.0.1) in Python. When running `handle = pvporcupine.create(access_key = ACCESS_KEY, keyword_paths=[model_path])` on one machine it works perfectly fine, however when I change to a different machine with the same access key and the same ppn model it hangs indefinitely at this line. The only difference between these 2 machines is that one usually need to set proxy bypass to access internet because it's behind a firewall. My question is, isn't the wake word detection supposed to work completely offline? What do you think could be the reason if internet is not the issue? Thank you

**Comment by kenarsa** [comment]
It should not hang indefinitely. If you can tell us about your network setup we can try to reproduce it on our end and push a fix/patch if applicable.

The voice recognition is offline but we do count the number of devices you deploy the SDK to. For that, we need internet connectivity. The connectivity does not need to be constant as we only perform occasional checks.

**Comment by yuanzhaoz** [comment]
> It should not hang indefinitely. If you can tell us about your network setup we can try to reproduce it on our end and push a fix/patch if applicable.
> 
> The voice recognition is offline but we do count the number of devices you deploy the SDK to. For that, we need internet connectivity. The connectivity does not need to be constant as we only perform occasional checks.

Thank you for your reply. It would be hard to describe our network setup as it has a firewall. Are you able to provide a list of IPs that the model is trying to access so that we can whitelist them? So far we have identified subnet addresses such as 18.66.180.xx. Are these static IP addresses or will they change dynamically in the future? I believe this could potentially be a problem for a lot of people if they are behind a university/company firewall. Thank you.

**Comment by yuanzhaoz** [comment]
> > It should not hang indefinitely. If you can tell us about your network setup we can try to reproduce it on our end and push a fix/patch if applicable.
> > The voice recognition is offline but we do count the number of devices you deploy the SDK to. For that, we need internet connectivity. The connectivity does not need to be constant as we only perform occasional checks.
> 
> Thank you for your reply. It would be hard to describe our network setup as it has a firewall. Are you able to provide a list of IPs that the model is trying to access so that we can whitelist them? So far we have identified subnet addresses such as 18.66.180.xx. Are these static IP addresses or will they change dynamically in the future? I believe this could potentially be a problem for a lot of people if they are behind a university/company firewall. Thank you.

If the IPs are not static, having a fixed DNS address might be really helpful so that people can simply whitelist that particular DNS. Could you please look into this as I believe other people are experiencing same issues? Thank you.

**Comment by laves** [comment]
@yuanzhaoz - we're having trouble recreating this on various firewall/network setups we've explored. Can you tell me what platform/OS you're experiencing this on? Before we provide our DNS address for whitelisting, we just want to ensure that we can patch the indefinite hang behaviour. Thank you.

**Comment by yuanzhaoz** [comment]
> @yuanzhaoz - we're having trouble recreating this on various firewall/network setups we've explored. Can you tell me what platform/OS you're experiencing this on? Before we provide our DNS address for whitelisting, we just want to ensure that we can patch the indefinite hang behaviour. Thank you.

Hi @laves It was tested on Ubuntu 18.04 and Ubuntu 20 machines when using Python API.

**Comment by laves** [comment]
Great, thanks. Can you try out [this porcupine lib file](https://github.com/Picovoice/porcupine/tree/timeout-patch/lib/linux/x86_64) with your setup? It should now timeout after about seven seconds. You can pass in a library file using the `--library_path` argument in either of the Python demos or, if you have your own application, with the `library_path=` Porcupine input argument.

**Comment by yuanzhaoz** [comment]
> Great, thanks. Can you try out [this porcupine lib file](https://github.com/Picovoice/porcupine/tree/timeout-patch/lib/linux/x86_64) with your setup? It should now timeout after about seven seconds. You can pass in a library file using the `--library_path` argument in either of the Python demos or, if you have your own application, with the `library_path=` Porcupine input argument.

Thank you @laves . However I think the problem for us is that it fails to reach the server you are using to authenticate the access key. It will always time out if it doesn't reach the server. Would it be possible for you to provide a DNS address for the users to whitelist? Thank you

**Comment by laves** [comment]
Yes, I'm sure that is the problem. You reported that the `create()` function hangs indefinitely as well though and we'd like to ensure our timeouts are working as expected. Since we can't recreate the hang you're experiencing, we'd appreciate it if you could try this patch out at let us know if you get an `ACTIVATION_ERROR` after some time. Once we can verify that, we'll move to testing the DNS address whitelist and add it to our documentation as well.

**Comment by yuanzhaoz** [comment]
> Yes, I'm sure that is the problem. You reported that the `create()` function hangs indefinitely as well though and we'd like to ensure our timeouts are working as expected. Since we can't recreate the hang you're experiencing, we'd appreciate it if you could try this patch out at let us know if you get an `ACTIVATION_ERROR` after some time. Once we can verify that, we'll move to testing the DNS address whitelist and add it to our documentation as well.

Thank you. I will test it out tomorrow as the machine is not currently with me. I will let you know the result soon as I go to the lab tomorrow.

**Comment by yuanzhaoz** [comment]
> Yes, I'm sure that is the problem. You reported that the `create()` function hangs indefinitely as well though and we'd like to ensure our timeouts are working as expected. Since we can't recreate the hang you're experiencing, we'd appreciate it if you could try this patch out at let us know if you get an `ACTIVATION_ERROR` after some time. Once we can verify that, we'll move to testing the DNS address whitelist and add it to our documentation as well.

Hi @laves  I have tried the lib file, it still hangs indefinitely. For reference this is my code:

`
import pvporcupine

ACCESS_KEY = 'xxx'
model_path = '/xxx/keyword_en_linux_v2_0_0.ppn'
handle = pvporcupine.create(access_key = ACCESS_KEY, library_path = '/xxx/libpv_porcupine.so', keyword_paths=[model_path])
`

Thanks

**Comment by laves** [comment]
Interesting - that's quite strange as we were able to see timeouts working over here with some restrictive firewall settings. At this point, we need to understand if this is a situation we need to address with a patch to our client or not. Can you test your wake word/context on the [Picovoice Console](https://console.picovoice.ai/) using your machine that's on the network in question? Does it hang or give you activation errors?

**Comment by fquirin** [comment]
Hi,

I'm having the same issue with the WASM lib using a vanilla JS webpage, but I think the reason is different. Its working fine outside of a web worker, but if I try to create the module inside a worker it hangs indefinitely at `pv_porcupine_init async` (_context12, step 76).
My best guess is that it fails because the worker is restricting access to localStorage where you seem to store the machine-id after successful access key validation.

If machine identification works via localStorage I see the next issue right away ... every time the browser cache will be cleared (which is every time I start my browser ...) you get a new machine ID and your key will be useless after 3 reloads. I'm already seeing 2 of 3 "devices" in my account although I've been using the same client with the same website ...

**Comment by kenarsa** [comment]
@fquirin I think there are good questions. Can you open a new issue for your questions? Trying to keep this thread exclusive for the issue opened by @yuanzhaoz which is related to Python SDK.

**Comment by fquirin** [comment]
Done: https://github.com/Picovoice/porcupine/issues/589

**Comment by yuanzhaoz** [comment]
> Interesting - that's quite strange as we were able to see timeouts working over here with some restrictive firewall settings. At this point, we need to understand if this is a situation we need to address with a patch to our client or not. Can you test your wake word/context on the [Picovoice Console](https://console.picovoice.ai/) using your machine that's on the network in question? Does it hang or give you activation errors?

@laves I have tried it and it works in the console. Currently I'm trying it in 2 ways on a machine that has whitelisted 18.66.180.xx addresses:
1. Running the script directly in a conda virtual environment. It works.
2. Running the script inside a docker container, it occasionally works, but most of the time it fails (failed completely yesterday and today). I have tried your patch lib file when inside docker container, no timeout error.

**Comment by laves** [comment]
@yuanzhaoz - we appreciate the investigation on your end. The network conditions you're working under are very difficult to reproduce and we have been unable to do so thus far. We've tried several university and company firewalls that we have access to and have always been able to get to our server or get proper timeouts. It is unlikely we can solve since any solution would be a shot in the dark at this point. For now, you can whitelist the DNS address `*.picovoice.net` for your development purposes and we'll keep an eye on related issues.

As for the docker container issue - that seems like a new issue. If you would like us to look into it, please post a separate issue with some details about your complete environment (machine, OS, versions, network conditions).

**Comment by kenarsa** [comment]
close due to inactivity. please re-open if needed

**Comment by garbit** [comment]
I'd like to reopen this issue given that the hanging timeout persists. I'm running the same setup as @yuanzhaoz inside the same network using python (different project).

I have requested `http://server-18-66-147-18.fra60.r.cloudfront.net/` and `18.66.147.18` to be whitelisted by our networks team however I think the IP has since changed. Is there no way you can host a DNS entry as part of the license check?
