### ISSUE TITLE
Porcupine Issue: inadvertently hit device limit despite only ever using one key and one device

### ISSUE THREAD

**Issue by Bazmundi** [Picovoice/porcupine#653]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Use of picovoice porcupine is allowed up to three devices.   That means, in my mind, a single key and perhaps 3 embedded devices distinguished by their MAC address or some other means of identifying a device uniquely.

### Actual behaviour
I appear to have hit a registration limit on the number of devices, but I have only been using software on one device.  A Raspberry Pi 3B+.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

I have been trying to track down why porcupine python demos don't work under Hypriot and Python 3.7.3.   To that end I have been reburning my SD card, swapping between Hypriot, Raspian (running Python 3.9.2) and back again - on the same device.

Otherwise I have only been trying to run the python demos both from mic input and by wav per https://github.com/Picovoice/porcupine/issues/649.  

That work is now halted.

The picovoice console is reporting I have 0 of 72000 seconds but 3 of 3 devices.   So I am assuming the system is seeing my latest activity as attempting to attach a forth device?   I certainly only have been using the key on one and only one device.   It otherwise appears the system has interpreted each re-burned SD sessions as a "different" device (somehow).    Is this lifting ssh keys or generating an alternate hidden companion key on first run, which may be different per re-burnt SD?

I don't appear to be able to delete the key and reset the account.   I can no longer use any devices, since all three appear to be defunct.

**Comment by kenarsa** [comment]
this behaviour is expected. every new OS install counts as one. I get why this is frustrating given you were trying to debug but it's the limitation of OS API for getting device UID. If you wait for 30-days the number of active devices will go back to 0 and you can keep working.

**Comment by Bazmundi** [comment]
> this behaviour is expected. every new OS install counts as one. I get why this is frustrating given you were trying to debug but it's the limitation of OS API for getting device UID. If you wait for 30-days the number of active devices will go back to 0 and you can keep working.

Ah!  Gotcha.

**Comment by abury** [comment]
Hi @kenarsa

I don't normally do this, but I need to say that this behavior is really disappointing. For iOS at least there are many more accurate ways to detect device limit. A limit of 3 individual installs when trying to debug without any ability to reset is **really really bad.** We've been using Picovoice to develop a demo app for the past 2 weeks, and we've been gearing up and testing it before a full day of demos today, and an hour before we were due to start, we performed another dry run, and now I've seen this as the error. We now have to do the entire day of demos without any of the voice activation functionality, you've left us dead in the water, for no real reason.

I understand a device limit for free accounts, and I understand that it's difficult to know what counts as an install across multiple device types, but being able to reset it manually, or pin a specific device really wouldn't be that hard on your end, and it would remove this type of issue.

**Comment by yezzer** [comment]
Yeah this is really disappointing. I've managed to hit the limit by reformatting and changing my raspberry pi's SD card. I see others have done the same. I can see why PV want to stop people abusing the limits, but 3 devices that reset after 30 days is extremely limiting for even hobbyists.

It is extremely good tech though!

**Comment by kenarsa** [comment]
@yezzer  we know this is a limitation on SBCs and we worked on a fix. The goal is to release the fix in the coming weeks. Stay tuned!

**Comment by yezzer** [comment]
@kenarsa that's really good to hear. Your tech is incredible - I really want to use it! 

Meanwhile, is there any way to find out when the 30 days timeout is up? I don't know when my initial activation was.
