### ISSUE TITLE
[Question] Access Token

### ISSUE THREAD

**Issue by Nailik** [Picovoice/porcupine#669]
Hello,

i am currently working on an Android implementation of Rhasspy (https://rhasspy.readthedocs.io/en/latest/), i'm sure you're familiar with this voice system.
However i am wondering why there is a need for an AccessKey also when i use BuildInKeywords only - more i am wondering how Rhasspy does this as there is no need to generate an AccessKey for Rhasspy. They write in their docs that a Picovoice account is only necessary if one want's to use custom keywords.

Did i miss something in the api documentation or do i have to prompt every user to generate an access token?

**Comment by laves** [comment]
Unfortunately the Rhasspy documentation on our products is quite out of date at this point. You will need to sign up for a [Picovoice Console account](https://console.picovoice.ai/) and obtain an `AccessKey` in order to develop with Porcupine, whether you use built-in or custom keywords. However, only you (as the developer) must have an `AccessKey` - your users don't need one. See our [Pricing page](https://picovoice.ai/pricing/) for additional information on our new usage-based license.

**Comment by Nailik** [comment]
Thanks for the fast update.
Just one more thing - what does the seconds of the access key stand for?

**Comment by laves** [comment]
'Seconds' is used for our products `Cheetah` and `Leopard`, which are charged by seconds of audio processed. `Porcupine` and `Rhino` are charged by active users/devices.
