### ISSUE TITLE
Enable to run Porcupine model on IMX8M nano board 

### ISSUE THREAD

**Issue by Kamilbentounes** [Picovoice/porcupine#857]
Hello!
 
We wanted to use the Porcupine WW model in the IMX8M nano board (you can find [here](https://www.mouser.fr/new/nxp-semiconductors/nxp-imx8m-nano-processor/) the link for the complete description).
 
We trained our custom models and generate them for both IMXRT, RPi. and Linux architectures.
 
We first implemented the python solution you give to run our custom models but got the following error: INVALID_ARGUMENT.  
 
We installed the Porcupine package using [this](https://pypi.org/project/pvporcupine/#files) prebuilt wheel.  
 
Since our board is an armv8, and the imx you give is for armv7, we don't know what kind of archi we have to use. 

The same application is running under RPi and PC Linux.
 
Alternatively, do we have to switch to the C version for Microcontroller? 

Can you please help us?
 
Thank you

**Comment by kenarsa** [comment]
@Kamilbentounes we do not support your board. the IMXRT build is for a totally different board (it's not an MPU, it's an MCU). You might be able to hack your way using RPI build as they are also armv8 but I can't help with that. If this is a commercial application and there is a budget you can reach out to Picovoice sales to see if they can help. Otherwise, we can't help out at this time.
