### ISSUE TITLE
AccessKey reached its device limit

### ISSUE THREAD

**Issue by vkjambit** [Picovoice/porcupine#899]
I'm developing an Android app with wakeword and it stopped working with "AccessKey reached its device limit"

I installed it on two devices and the picovoice console is only saying my license is active on one device.

**Comment by ksyeo1010** [comment]
Can you provide more details? Is it the same app that threw the error? Are you saying picovoice console is showing the wrong number of active devices?

**Comment by vkjambit** [comment]
i didn't change anything on the device, just didn't use it for 2 or 3 weeks. our product is currently in development and my business-partner and one tester also has a device. 
oh but i remember now that my business partner has his own picovoice key which i compiled in his code. the tester uses the same key as me. in the console is shown that i only have one active device.

**Comment by ksyeo1010** [comment]
can you make sure it is the same access key? if it is, can you mail your access key to `hello@picovoice.ai`  so we can investigate further?

**Comment by vkjambit** [comment]
i will send you the keys thanks!

**Comment by veitk** [comment]
any news?

**Comment by ksyeo1010** [comment]
Using multiple accounts to work on the same project in order to circumvent the pricing structure violates Picovoice's [Terms of Use](https://picovoice.ai/docs/terms-of-use/). The system automatically detects accounts that have not been compliant and disables them. If you think this is a mistake feel free to send an email to hello@picovoice.ai with your justification.
