### ISSUE TITLE
Porcupine Issue: Used on Electron, init() always reports failed with 'INVALID_ARGUMENT'

### ISSUE THREAD

**Issue by Mickeygogo** [Picovoice/porcupine#959]
I used a simple example on electron：

   const initEngine = async () => {
    await init(
      accessKey,
      [BuiltInKeyword.Alexa],
      {publicPath: ''}
    );
  }

Execution continues to report errors：
loading parameters failed with `INVALID_ARGUMENT`

I'm a developer from China and I need to solve this problem urgently

**Comment by Mickeygogo** [comment]
electron + react

**Comment by mrrostam** [comment]
It seems like the issue is related to the `publicPath` parameter being empty in the init function call, which is causing the model to not be found. I suggest checking the [documentation on the website](https://picovoice.ai/docs/quick-start/porcupine-react/) or the [demo on Github](https://github.com/Picovoice/porcupine/tree/master/demo/react) to make sure the publicPath parameter is set correctly.
