### ISSUE TITLE
Allow IPA to be passed to keyword generator

### ISSUE THREAD

**Issue by Qix-** [Picovoice/Porcupine#96]
Without source, it's not entirely clear what you're using to generate pronunciations but it would be wildly helpful for both users and maintainers if you allowed not only the `-w` keyword but something like `-i, --ipa` to be able to supply an [IPA pronunciation](https://en.wiktionary.org/wiki/Wiktionary:IPA_pronunciation_key) string in lieu of English words. This would allow the training of any keyword imaginable without the need to maintain a list.

That would also get rid of the [slew of missing keyword issues](https://github.com/Picovoice/Porcupine/issues?utf8=%E2%9C%93&q=Pronunciation) problem.

e.g.

```console
$ pv_porcupine_optimizer -w 'argonaut'
[ERROR] could not find the pronunciation for 'argonaut'
--> 1

$ pv_porcupine_optimizer --ipa 'ɑːrɡənɔːt'
--> 0
```

<sup>(yes I'm aware `argonaut` works by default, it was the first random Wikipedia page that had an IPA readily available 🙃)</sup>

**Comment by kenarsa** [comment]
Totally understand the point. We did think about this option at the beginning and we decided not to go down this path. The reason is that we rather users to be limited than be able to make mistakes and not get the results they expect. Especially that the commercial customers we have are also using the optimizer tool to create models for evaluation. We just rather them to come to us and ask for their specific keyword that is not available rather than creating a model with incorrect phonemes.

**Comment by Qix-** [comment]
But how is that maintainable? Releasing something under a license as liberal as apache grants you a bit of leeway with "hey, if you supply a bizarre word you might not get the results you want" rather than completely limiting the word choices.

Further it hurts adoption with teams that would like to use a wake word that is a prototypical/code name. It makes very little sense to "open source" a bunch of binaries without source and _still_ limit users on which words they use.

It's great technology but a bizarre set of restrictions you're placing in order to pass as OSS.
